Hw 01 dev
akhoroshev/se-architecture-course pull request #1
Opened 2019-02-24 12:24 UTC by akhoroshev

2019-03-20 17:09 UTC, ottergottaott requested changes
В целом код мне понравился, выделение команд в отдельную иерархию -- хорошее решение, но есть некоторые замечания и недоделки.

Интерполяция в двойными кавычками не совсем валидно работает:
```
> a=1
> echo "asdasd$a"
asdasd$a
```
Ожидается
```
> a=1
> echo "asdasd$a"
asdasd1
```

`git status` повесил shell, хотелось бы избегать этого :)

2019-03-20 17:09 UTC, ottergottaott commented on src/cli_executor.py
> +    def add_command(self, command_constructor, name: str, infix: bool):
В целом большой плюсик за использование type hints, но если начал их писать, то лучше дописывать везде, особенно, если это `Callable`.

В данном конкретном случае отсутствие вразумительного type hint ведет к двум вещам:
1) Пользователю, использующему в коде `CliExecutor`, не очевидно какой именно constructor нужно передать и каким гарантиям он должен удовлетворять, придется смотреть весь код, чтобы это выяснить
2) В переданный конструктор при вызове очень легко случайно подать неправильный набор аргументов(думаю, это и так ясно)

Вообще с типами очень хорошее правило: если ты не можешь для передаваемого аргумента выбрать конкретный тип, то что-то уже невпорядке

Предлагаю это исправить или хотя бы подумать(и ответить:)) над тем, как это можно было бы сделать

2019-03-20 17:09 UTC, ottergottaott commented on src/cli_executor.py
> +            except Exception as e:
Не устану повторять, но `try/catch`, ловящий `Exception` -- это плохо и малоинформативно

А еще в данном случае это вполне следствие упомянутой выше проблемы с type hints. Например, если бы в коде можно было узнать, что вызов конструктора команды с таким количеством аргументов невозможен, сюда бы пришла более вразумительная ошибка с полезной для пользователя информацией

2019-03-20 17:09 UTC, ottergottaott commented on src/preprocessor.py
> +def split_whitespace(string: str) -> [str]:
Я бы вынес эти функции в какой-нибудь отдельный модуль либо спрятал только в `PreprocessorImpl`, потому что так они повисли в месте, откуда ожидаешь видеть только  `PreprocessorImpl` и `IPreprocessor`.

2019-03-20 17:09 UTC, ottergottaott commented on src/preprocessor.py
> +def split_symbols(string: str) -> [str]:
Также у всех этих методов не хватает документации.

2019-03-20 17:09 UTC, ottergottaott commented on tests/test_IEnvironment.py
> +class TestIEnvironment(TestCase):
Очень не хватает тестов для утилит: `cat`, `wc` и т.д.

2019-03-20 17:09 UTC, ottergottaott commented on src/commands/callback.py
> +    def __init__(self, action, number_of_params, name, *args):
Таже история с type hints

2019-03-20 17:09 UTC, ottergottaott commented on src/environment.py
> +# Implementation #
Плашечка красивая, но не информативная от слова совсем :)

Было бы хорошо увидеть более осмысленный комментарий с некоторыми особенностями именно этой имплементации, по типу "environment реализованный с ипользованием на dict"

2019-03-20 17:09 UTC, ottergottaott commented on src/environment.py
> +class IEnvironment(ABC):
Тут не хватает комментария еще больше, чем у имплементации

2019-03-20 17:09 UTC, ottergottaott commented on src/parser.py
> +# Implementation #
Аналогично

2019-03-20 17:09 UTC, ottergottaott commented on src/parser.py
> +def eat_prefix_whitespaces(array: list) -> list:
Опять "повисшие" методы

2019-03-20 17:09 UTC, ottergottaott commented on src/commands/callback.py
> +class Callback(ICommand):
`Callback` -- очень общее название, я пока не придумал лучше, но предлагаю подумать над более конкретным

2019-03-20 17:09 UTC, ottergottaott commented on src/commands/wc.py
> +class Stat:
Тут снова комментарии

2019-03-20 17:09 UTC, ottergottaott commented on src/commands/callback.py
> +class Callback(ICommand):
А еще опять не хватает комментариев :)

2019-03-20 17:09 UTC, aleksZubakov commented on src/command.py
> +    m_current_dir = None
_Не обзательное к исправлению замечание:_
Кажется, что лучше все-таки держать текущую директорию в `Environment`, это больше похоже на его ответственность + если предоставить разумный интерфейс в Environment, через который можно изменять директорию, будет проще отслеживать кто и когда полез менять ее и, как следствие, писать тесты(накидав mock object)

2019-03-20 17:11 UTC, aleksZubakov commented
А еще бы хорошо сделать полноценные packages https://docs.python.org/3.6/tutorial/modules.html#packages

2019-06-16 15:49 UTC, akhoroshev commented on src/cli_executor.py
> +    def add_command(self, command_constructor, name: str, infix: bool):
Добавил везде type hints

2019-06-16 16:16 UTC, akhoroshev commented
@aleksZubakov 
Я постарался исправить твои замечания.
Однако, гитхаб глючит, и я не могу запросить твою ревью повторно

2019-06-16 16:17 UTC, akhoroshev commented
> git status повесил shell, хотелось бы избегать этого :)

у меня не виснет :)

у меня вообще работает nano/vim и тд

2019-06-17 18:51 UTC, yurii-litvinov approved these changes
В целом всё ок, так что я считаю, что можно зачесть

2019-06-17 18:51 UTC, yurii-litvinov commented on architecture/README.md
> + выходной стрим одной команды в качестве входного другой (pipe)
Диаграмму тоже сюда куда-нибудь прилинковать имело бы смысл, чтобы она не лежала отдельно

2019-06-17 18:51 UTC, yurii-litvinov commented on src/cli_executor.py
> +class CliExecutor:
Комментарии к самому классу даже нужнее, чем к его методам, потому что первое, что хочет выяснить читатель, это "что это вообще" а не "что и как оно умеет делать"

2019-06-17 18:57 UTC, closed without merging