Hw 02 dev
akhoroshev/se-architecture-course pull request #2
Opened 2019-03-03 19:05 UTC by akhoroshev

2019-04-06 13:03 UTC, ottergottaott requested changes
- Отсутствует обоснования выбора `argparse` в качестве библиотеки для парсинга аргументов
- Ожидается, что такой код не будет работать, как сейчас:
```
> grep -A -1 pip Dockerfile
RUN pip install -r requirements.txt
```
и выведет что-то подобное
```
> grep -A -1 pip Dockerfile 
grep: -1: invalid context length argument
```
- нет тестов, покрывающих именно `grep`
Еще на будущее: старайся делать pr, в котором есть только актуальные для него коммиты. В данном случае это можно было бы сделать создав pr не в ветку `master`, а в `hw_01_dev`

2019-04-06 13:03 UTC, ottergottaott commented on src/commands/grep.py
> +class Grep(IFsCommand):
Не хватает комментариев всем классам в этом файле :)

2019-04-06 13:03 UTC, aleksZubakov commented on src/commands/grep.py
> +        if input_name:
Я бы переписал этот кусоче так:
```python 
if not input_name:
    return grep(self.m_inp_stream)
with open(input_name, "r") as file:
    return grep(file)
```

Меньше вложенность -- проще читать, функцию `grep` тоже бы вынес и назвал `__grep`

2019-06-17 11:35 UTC, akhoroshev commented
@aleksZubakov 
Пофикшено

2019-06-17 19:09 UTC, yurii-litvinov approved these changes
В целом ок, можно зачесть.

2019-06-17 19:09 UTC, yurii-litvinov commented on src/commands/grep.py
> +    Argparse makes life easy by providing us a way to define the commonly used validations for command line arguments.
Ну, а какие ещё библиотеки рассматривались? Для Питона есть пара интересных опций в этом плане. За "взяли либу такую-то, потому что это первое, что попалось/мы всю жизнь её использовали" больно накажут на защите ВКР, как минимум.

2019-06-17 19:10 UTC, closed without merging