Hw 03 dev
akhoroshev/se-architecture-course pull request #3
Opened 2019-03-09 16:08 UTC by akhoroshev

2019-05-28 08:58 UTC, yurii-litvinov requested changes
По контекстной IDEF0-диаграмме:
- снизу в процесс должны входить внешние по отношению к нему механизмы, это скорее оборудование и рабочие, чем конкретные виды конвейеров
- сверху --- внешнее управление. "План производства" и "План испытаний", скорее всего, внутреннее дело завода, если у нас не плановая экономика. "Комплектация" и "Цвет", скорее всего, части заказов. Тут было бы лучше что-то вроде "Отраслевые стандарты" и "Государственные законы"
- вообще не отображён результат процесса

По диаграмме первого уровня:
- на диаграмме IDEF0 первого уровня все стрелки извне должны были встречаться и на контекстной диаграмме и называться именно так, как там. Основной смысл IDEF0 в иерархической декомпозиции, так что каждая диаграмма является раскрытием одного блока предыдущей и при этом всегда можно отследить, что откуда пришло. 
- процесс "Производство автомобиля" вряд ли перерабатывает планы в автомобили. Я бы нарисовал план как управление, а входы --- это комплектующие.
- а если автомобиль не прошёл испытания?

По BPMN-диаграмме:
- "Получение плана производства" и "Подготовка испытания" зря содержат конвертики, они, судя по диаграмме, никаких сообщений не принимают. Сообщения рисуются пунктирными стрелками и могут быть только между пулами.
- После действия "Возврат на конвейер", судя по диаграмме, процесс завершается. Если буквально интерпретировать эту диаграмму, на конвейере скопится гора отремонтированных автомобилей, с которыми никто больше ничего не делает
- окончание бизнес-процесса зря в ромбе. Ромбы в BPMN --- это ветвления.

Use-case диаграммы нге хватает.

2019-06-18 16:09 UTC, yurii-litvinov requested changes
- "Загруженность конвейера" тоже внутреннее дело завода, а не внешнее управление
- Use Case диаграмма содержит какие-то облачка, противоречащие синтаксису языка, зато не содержит границы системы. Посмотрите https://www.uml-diagrams.org/use-case-diagrams.html

2019-06-18 20:05 UTC, akhoroshev commented
@yurii-litvinov 
пофиксил.
Верно ли я понял, что на idef01 диаграмме не может быть совершенно новых внешних входов, относительно idef00?

2019-06-19 06:34 UTC, yurii-litvinov commented
Да, теперь всё правильно.

>Верно ли я понял, что на idef01 диаграмме не может быть совершенно новых внешних входов, относительно idef00?

Ага, idef0 фактически построен вокруг иерархичности и трассируемости --- вся фишка стандарта в том, что всегда можно проследить, что откуда пришло.

2019-06-19 19:17 UTC, closed without merging