Hw 04 dev
akhoroshev/se-architecture-course pull request #4
Opened 2019-03-10 11:12 UTC by StanislavSychev

2019-06-13 23:33 UTC, artbez requested changes
Не хватает тестов
Нужно добавить ревью архитектуры
Нужно добавить комментарии

2019-06-13 23:33 UTC, artbez commented on src/commands/ls.py
> +        print(" ".join(res), file=self.m_out_stream)
Лучше join делать на "\n". Удобней смотреть результат.

2019-06-13 23:33 UTC, artbez commented on src/commands/cd.py
> +            new_dir = join(IFsCommand.m_current_dir, new_dir)
Если new_dir = ../.. , получим /old/path/before/../.. вместо /old

2019-06-13 23:33 UTC, artbez commented on src/commands/cd.py
> +            new_dir = join(IFsCommand.m_current_dir, new_dir)
Тут тоже сплитить нужно

2019-06-13 23:33 UTC, artbez commented on src/commands/ls.py
> +    def execute(self) -> None:
ls должна уметь выводить содержимое указанной папки. Например, ls src должно вывести все файлы в папке src. Если такой папки нет, нужно ругаться

2019-06-16 19:12 UTC, StanislavSychev commented on src/commands/ls.py
> +        print(" ".join(res), file=self.m_out_stream)
сделал на "\n"

2019-06-16 19:13 UTC, StanislavSychev commented on src/commands/cd.py
> +            new_dir = join(IFsCommand.m_current_dir, new_dir)
"../.." это последний случай, питон сам такое умеет обрабатывать оказывается.

2019-06-16 19:13 UTC, StanislavSychev commented on src/commands/ls.py
> +    def execute(self) -> None:
добавил эту функцию

2019-06-16 19:48 UTC, artbez commented on src/commands/cd.py
> +            new_dir = join(IFsCommand.m_current_dir, new_dir)
Да, он обрабатывается, согласен. Но не совсем корректно:) Пример.

> pwd
/Users/artemii/Study/ITMO/horoshev/se-architecture-course
> cd ../..
> pwd
/Users/artemii/Study/ITMO/horoshev/se-architecture-course/../..
> cd ..
> pwd
/Users/artemii/Study/ITMO/horoshev/se-architecture-course/..

2019-06-16 21:13 UTC, StanislavSychev commented on src/commands/cd.py
> +            new_dir = join(IFsCommand.m_current_dir, new_dir)
теперь обрабатывает корректно

2019-06-17 15:47 UTC, yurii-litvinov approved these changes
Внешние команды ничего не знают про cd. Например, если несколько раз сделать `cd ..`, затем `git status`, git всё ещё выведет информацию об исходной папке. Но ладно, в остальном всё ок, зачтена

2019-06-20 10:42 UTC, closed without merging